stages:
  - buildrelease

linux64:
  image: amityproject/linux64:builder
  stage: buildrelease
  script:
  - git submodule init && git submodule update
  - make release-static


win64:
  image: amityproject/win64:builder
  stage: buildrelease
  script:
  - git submodule init && git submodule update
  - cd contrib/depends/
  - make download
  - cd ../..
  - make depends target=x86_64-w64-mingw32


macos64:
  image: amityproject/macos:builder
  stage: buildrelease
  script:
  - git submodule init && git submodule update
  - cd contrib/depends/
  - make download
  - cd ../..
  - make depends target=x86_64-apple-darwin11
  artifacts:
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd


arm64:
  image: amityproject/aarch64:builder
  stage: buildrelease
  script:
  - git submodule init && git submodule update
  - cd contrib/depends/
  - make download
  - cd ../..
  - make depends target=aarch64-linux-gnu
  artifacts:
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd 

armhf:
  image: amityproject/arm:builder
  stage: buildrelease
  script:
  - git submodule init && git submodule update
  - cd contrib/depends/
  - make download
  - cd ../..
  - make depends target=arm-linux-gnueabihf
  artifacts:
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd

riscv64:
  image: amityproject/riscv64:builder
  stage: buildrelease
  script:
  - git submodule init && git submodule update
  - cd contrib/depends/
  - make download
  - cd ../..
  - make depends target=riscv64-linux-gnu
  artifacts:
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd