stages:
  - buildrelease
  - deploy

linux64:
  image: amityproject/linux64:builder
  stage: buildrelease
  script:
  - git submodule init && git submodule update
  - make release-static
  except:
    - master

  
linux64-deploy:
  image: amityproject/linux64:builder
  stage: deploy
  script:
  - git submodule init && git submodule update
  - make release-static
  - mv ./build/release/bin/* ./
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA"
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd
  only:
    - master


win64:
  image: amityproject/win64:builder
  stage: buildrelease
  script:
  - git submodule init && git submodule update
  - cd contrib/depends/
  - make download-win
  - cd ../..
  - make depends target=x86_64-w64-mingw32
  except:
    - master

  
win64-deploy:
  image: amityproject/win64:builder
  stage: deploy
  script:
  - git submodule init && git submodule update
  - cd contrib/depends/
  - make download-win
  - cd ../..
  - make depends target=x86_64-w64-mingw32
  - mv ./build/x86_64-w64-mingw32/release/bin/* ./
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA"
    paths:
    - ./amity-blockchain-import.exe
    - ./amity-blockchain-export.exe
    - ./amity-wallet-cli.exe
    - ./amity-wallet-rpc.exe
    - ./amityd.exe
  only:
    - master


macos64:
  image: amityproject/macos:builder
  stage: buildrelease
  script:
  - git submodule init && git submodule update
  - cd contrib/depends/
  - make download-osx
  - cd ../..
  - make depends target=x86_64-apple-darwin11
  except:
    - master


macos64-deploy:
  image: amityproject/macos:builder
  stage: deploy
  script:
  - git submodule init && git submodule update
  - cd contrib/depends/
  - make download-osx
  - cd ../..
  - make depends target=x86_64-apple-darwin11
  - mv ./build/x86_64-apple-darwin11/release/bin/* ./
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA"
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd
  only:
    - master


arm64:
  image: amityproject/aarch64:builder
  stage: buildrelease
  script:
  - git submodule init && git submodule update
  - cd contrib/depends/
  - make download-osx
  - cd ../..
  - make depends target=aarch64-linux-gnu
  except:
    - master


arm64-deploy:
  image: amityproject/aarch64:builder
  stage: deploy
  script:
  - git submodule init && git submodule update
  - cd contrib/depends/
  - make download
  - cd ../..
  - make depends target=aarch64-linux-gnu
  - mv ./build/aarch64-linux-gnu/release/bin/* ./  
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA"
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd
  only:
    - master

armhf:
  image: amityproject/armhf:builder
  stage: buildrelease
  script:
  - git submodule init && git submodule update
  - cd contrib/depends/
  - make download-linux
  - cd ../..
  - make depends target=arm-linux-gnueabihf
  except:
    - master


armhf-deploy:
  image: amityproject/armhf:builder
  stage: deploy
  script:
  - git submodule init && git submodule update
  - cd contrib/depends/
  - make download-linux
  - cd ../..
  - make depends target=arm-linux-gnueabihf
  - mv ./build/arm-linux-gnueabihf/release/bin/* ./ 
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA"
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd
  only:
    - master

riscv64:
  image: amityproject/riscv64:builder
  stage: buildrelease
  script:
  - git submodule init && git submodule update
  - cd contrib/depends/
  - make download-linux
  - cd ../..
  - make depends target=riscv64-linux-gnu
  except:
    - master


riscv64-deploy:
  image: amityproject/riscv64:builder
  stage: deploy
  script:
  - git submodule init && git submodule update
  - cd contrib/depends/
  - make download-linux
  - cd ../..
  - make depends target=riscv64-linux-gnu
  - mv ./build/riscv64-linux-gnu/release/bin/* ./ 
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA"
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd
  only:
    - master
    