stages:
  - build
  - deploy

linux64:
  image: amityproject/ubuntu:builder
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - make release-static
  except:
    - tags

  
LINUX64:
  image: amityproject/ubuntu:builder
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - make release-static
  - mv ./build/release/bin/* ./
  artifacts:
    name: "Amity-$CI_COMMIT_TAG-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd
  only:
    - tags


win64:
  image: amityproject/ubuntu:builder
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - rm -r contrib/depends
  - cd contrib 
  - cp -r ~/depends ./
  - cd ../
  - make depends target=x86_64-w64-mingw32
  except:
    - tags

  
WIN64:
  image: amityproject/ubuntu:builder
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - rm -r contrib/depends
  - cd contrib 
  - cp -r ~/depends ./
  - cd ../
  - make depends target=x86_64-w64-mingw32
  - mv ./build/x86_64-w64-mingw32/release/bin/* ./
  artifacts:
    name: "Amity-$CI_COMMIT_TAG-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
    - ./amity-blockchain-import.exe
    - ./amity-blockchain-export.exe
    - ./amity-wallet-cli.exe
    - ./amity-wallet-rpc.exe
    - ./amityd.exe 
  only:
    - tags


macos64:
  image: amityproject/macos:builder
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - make release 
  tags:
    - macos
  only:
    - branches


MACOS64:
  image: amityproject/macos:builder
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - make release
  - mv ./build/release/bin/* ./
  artifacts:
    name: "Amity-$CI_COMMIT_TAG-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd   
  tags:
    - macos
  only:
    - tags
  except:
    - branches


arm64:
  image: amityproject/ubuntu:builder
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - rm -r contrib/depends
  - cd contrib 
  - cp -r ~/depends ./
  - cd ../
  - make depends target=aarch64-linux-gnu
  except:
    - tags


ARM64:
  image: amityproject/ubuntu:builder
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - rm -r contrib/depends
  - cd contrib 
  - cp -r ~/depends ./
  - cd ../
  - make depends target=aarch64-linux-gnu
  - mv ./build/aarch64-linux-gnu/release/bin/* ./  
  artifacts:
    name: "Amity-$CI_COMMIT_TAG-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd  
  only:
    - tags

armhf:
  image: amityproject/ubuntu:builder
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - rm -r contrib/depends
  - cd contrib 
  - cp -r ~/depends ./
  - cd ../
  - make depends target=arm-linux-gnueabihf
  except:
    - tags


ARMHF:
  image: amityproject/ubuntu:builder
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - rm -r contrib/depends
  - cd contrib 
  - cp -r ~/depends ./
  - cd ../
  - make depends target=arm-linux-gnueabihf
  - mv ./build/arm-linux-gnueabihf/release/bin/* ./ 
  artifacts:
    name: "Amity-$CI_COMMIT_TAG-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd
  only:
    - tags


riscv64:
  image: amityproject/ubuntu:builder
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - rm -r contrib/depends
  - cd contrib 
  - cp -r ~/depends ./
  - cd ../
  - make depends target=riscv64-linux-gnu
  except:
    - tags


RISCV64:
  image: amityproject/ubuntu:builder
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - rm -r contrib/depends
  - cd contrib 
  - cp -r ~/depends ./
  - cd ../
  - make depends target=riscv64-linux-gnu
  - mv ./build/riscv64-linux-gnu/release/bin/* ./ 
  artifacts:
    name: "Amity-$CI_COMMIT_TAG-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
    - ./amity-blockchain-import
    - ./amity-blockchain-export
    - ./amity-wallet-cli
    - ./amity-wallet-rpc
    - ./amityd
  only:
    - tags
    